favicon: null
name: Mulia Legacy
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 0.40681
  brandColors:
    - '#FFFFFF'
    - '#FFFF77'
    - '#24272E'
    - '#6B6C6E'
    - '#8A8D92'
  lightness: 0.2311828
typography_spectrum: 0.4265233
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
