favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.5179211
  brandColors:
    - '#C6C7C1'
    - '#0F1014'
    - '#FFFFFD'
    - '#979A93'
    - '#D2741C'
  rhythmicContrast: 0
typography_spectrum: 0.4265233
layout_spectrum: 0.3763441
analytics:
  twitter: null
  google: null
  facebook: null
name: Mulia Legacy
